name: "Sync GitHub stars with Raindrop"
on:
  schedule:
    - cron: "13 18 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - name: Build
        run: npm run build

      - name: run script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          RAINDROP_TOKEN: ${{ secrets.RAINDROP_TOKEN }}
          RAINDROP_COLLECTION_ID: ${{ secrets.RAINDROP_COLLECTION_ID }}
        run: node src/script.js
